DROP TABLE IF EXISTS proj.stock;
DROP TABLE IF EXISTS proj.order_line;
DROP TABLE IF EXISTS proj.item;
DROP TABLE IF EXISTS proj.orders;
DROP TABLE IF EXISTS proj.customer;
DROP TABLE IF EXISTS proj.district;
DROP TABLE IF EXISTS proj.warehouse;
DROP DATABASE IF EXISTS proj;